# Generated by Django 4.2.5 on 2023-11-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('deadline', models.CharField(max_length=200)),
                ('priority', models.CharField(blank=True, choices=[('!', 'Low Priority'), ('!!', 'Regular Priority'), ('!!!', 'High Priority')], max_length=200)),
            ],
        ),
    ]
