# Generated by Django 4.2.5 on 2023-11-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0002_assignment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
